# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_vision_ops_nms <- function(dets, scores, iou_threshold) {
    .Call(`_torchvisionlib_rcpp_vision_ops_nms`, dets, scores, iou_threshold)
}

rcpp_vision_ops_deform_conv2d <- function(input, weight, offset, mask, bias, stride_h, stride_w, pad_h, pad_w, dilation_h, dilation_w, groups, offset_groups, use_mask) {
    .Call(`_torchvisionlib_rcpp_vision_ops_deform_conv2d`, input, weight, offset, mask, bias, stride_h, stride_w, pad_h, pad_w, dilation_h, dilation_w, groups, offset_groups, use_mask)
}

rcpp_vision_ops_ps_roi_align <- function(input, rois, spatial_scale, pooled_height, pooled_width, sampling_ratio) {
    .Call(`_torchvisionlib_rcpp_vision_ops_ps_roi_align`, input, rois, spatial_scale, pooled_height, pooled_width, sampling_ratio)
}

rcpp_vision_ops_ps_roi_pool <- function(input, rois, spatial_scale, pooled_height, pooled_width) {
    .Call(`_torchvisionlib_rcpp_vision_ops_ps_roi_pool`, input, rois, spatial_scale, pooled_height, pooled_width)
}

rcpp_vision_ops_roi_align <- function(input, rois, spatial_scale, pooled_height, pooled_width, sampling_ratio, aligned) {
    .Call(`_torchvisionlib_rcpp_vision_ops_roi_align`, input, rois, spatial_scale, pooled_height, pooled_width, sampling_ratio, aligned)
}

rcpp_vision_ops_roi_pool <- function(input, rois, spatial_scale, pooled_height, pooled_width) {
    .Call(`_torchvisionlib_rcpp_vision_ops_roi_pool`, input, rois, spatial_scale, pooled_height, pooled_width)
}

rcpp_vision_read_jpeg <- function(fpath) {
    .Call(`_torchvisionlib_rcpp_vision_read_jpeg`, fpath)
}

rcpp_vision_read_jpeg_float <- function(fpath) {
    .Call(`_torchvisionlib_rcpp_vision_read_jpeg_float`, fpath)
}

rcpp_delete_tensor_pair <- function(x) {
    invisible(.Call(`_torchvisionlib_rcpp_delete_tensor_pair`, x))
}

rcpp_tensor_pair_get_first <- function(x) {
    .Call(`_torchvisionlib_rcpp_tensor_pair_get_first`, x)
}

rcpp_tensor_pair_get_second <- function(x) {
    .Call(`_torchvisionlib_rcpp_tensor_pair_get_second`, x)
}

#' Multiscale Deformable Attention Forward Pass
#'
#' @param value Input tensor (value)
#' @param spatial_shapes Input tensor (spatial_shapes)
#' @param level_start_index Input tensor (level_start_index)
#' @param sampling_loc Input tensor (sampling_loc)
#' @param attn_weight Input tensor (attn_weight)
#' @param im2col_step Integer (im2col_step)
#' @return Output tensor
#' @keywords internal
NULL

#' Multiscale Deformable Attention Backward Pass
#'
#' @param value Input tensor (value)
#' @param spatial_shapes Input tensor (spatial_shapes)
#' @param level_start_index Input tensor (level_start_index)
#' @param sampling_loc Input tensor (sampling_loc)
#' @param attn_weight Input tensor (attn_weight)
#' @param grad_output Input tensor (grad_output)
#' @param im2col_step Integer (im2col_step)
#' @return A list of gradient tensors (grad_value, grad_sampling_loc, grad_attn_weight)
#' @keywords internal
NULL

ms_deform_attn_forward_cpp <- function(value, spatial_shapes, level_start_index, sampling_loc, attn_weight, im2col_step) {
    .Call(`_torchvisionlib_ms_deform_attn_forward_cpp`, value, spatial_shapes, level_start_index, sampling_loc, attn_weight, im2col_step)
}

ms_deform_attn_backward_cpp <- function(value, spatial_shapes, level_start_index, sampling_loc, attn_weight, grad_output, im2col_step) {
    .Call(`_torchvisionlib_ms_deform_attn_backward_cpp`, value, spatial_shapes, level_start_index, sampling_loc, attn_weight, grad_output, im2col_step)
}

